# Generated by Django 4.1.7 on 2023-02-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("NTN", models.CharField(max_length=20)),
                ("STRN", models.CharField(max_length=20)),
                ("GST", models.FloatField()),
                ("email", models.EmailField(max_length=254)),
                ("contact", models.CharField(max_length=20)),
                ("address", models.TextField()),
                ("logo", models.TextField()),
            ],
        ),
    ]
