# Generated by Django 4.1.7 on 2023-02-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="contact",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
