# Generated by Django 4.1.7 on 2023-02-27 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_alter_company_contact_alter_company_name"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="company",
            table="company",
        ),
    ]
