# Generated by Django 4.1.7 on 2023-03-07 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0006_delete_company_bracnch_user"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="bracnch",
            table="branch",
        ),
        migrations.AlterModelTable(
            name="employee",
            table="employee",
        ),
    ]
